#!/usr/bin/env python3
"""Project-agnostic reference index generator.

Walks a project's reference/ directory, reads each markdown file's YAML
frontmatter (and H1) to build a categorized index.md. Unlike the per-project
bespoke generators (which hardcode title mappings), this reads titles/tags from
the files themselves, so it works for ANY project's reference/ with zero setup.

Used by the unified Discord intake pipe as the fallback index step when the
target project has no bespoke update_reference_index.py.

Usage:
    python3 heaven/tools/build_reference_index.py projects/<name>/reference
    python3 heaven/tools/build_reference_index.py <dir> --stdout   # preview, no write

Category = the top-level subdirectory under <reference_dir>. Files placed
directly in <reference_dir> go under "ルート". The `_inbox/` bucket (unclassified
/ 要確認 captures from intake) is always surfaced first so triage is visible.
"""
from __future__ import annotations

import argparse
import os
import sys
from datetime import datetime, timezone


def parse_frontmatter(text: str) -> dict[str, str]:
    """Minimal YAML frontmatter parser (key: value). No pyyaml dependency.

    Returns {} when the file has no leading `---` frontmatter block.
    """
    if not text.startswith("---"):
        return {}
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    meta: dict[str, str] = {}
    for line in lines[1:]:
        if line.strip() == "---":
            break
        if ":" in line:
            key, _, val = line.partition(":")
            meta[key.strip()] = val.strip()
    return meta


def first_h1(text: str) -> str | None:
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("# "):
            return s[2:].strip()
    return None


def title_for(path: str, text: str) -> str:
    meta = parse_frontmatter(text)
    return meta.get("title") or first_h1(text) or os.path.splitext(os.path.basename(path))[0]


def category_for(rel: str) -> str:
    """Top-level subdir under reference_dir, or 'ルート' for top-level files."""
    parts = rel.split(os.sep)
    if len(parts) == 1:
        return "ルート"
    return parts[0]


def build_index(reference_dir: str) -> str:
    reference_dir = os.path.normpath(reference_dir)
    project = os.path.basename(os.path.dirname(reference_dir)) or os.path.basename(reference_dir)

    categories: dict[str, list[tuple[str, str]]] = {}
    for root, _dirs, files in os.walk(reference_dir):
        for fn in sorted(files):
            if not fn.endswith(".md") or fn == "index.md":
                continue
            full = os.path.join(root, fn)
            rel = os.path.relpath(full, reference_dir)
            try:
                with open(full, encoding="utf-8") as f:
                    text = f.read()
            except OSError:
                continue
            meta = parse_frontmatter(text)
            title = meta.get("title") or first_h1(text) or os.path.splitext(fn)[0]
            tags = meta.get("tags", "")
            suffix = f" — {tags}" if tags else ""
            entry = (f"- [{title}]({rel.replace(os.sep, '/')}){suffix}", rel)
            categories.setdefault(category_for(rel), []).append(entry)

    def cat_sort_key(name: str) -> tuple[int, str]:
        # _inbox first (triage visibility), ルート last, others alphabetical.
        if name == "_inbox":
            return (0, "")
        if name == "ルート":
            return (2, "")
        return (1, name)

    out = [f"# {project} Reference Index", ""]
    for cat in sorted(categories, key=cat_sort_key):
        heading = "未整理 / 要確認 (_inbox)" if cat == "_inbox" else cat
        out.append(f"## {heading}")
        for line, _rel in sorted(categories[cat]):
            out.append(line)
        out.append("")

    if not categories:
        out.append("_（まだ記録がありません）_")
        out.append("")

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    out.append("---")
    out.append(f"*最終更新日: {today} (UTC) / generated by build_reference_index.py*")
    out.append("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description="Project-agnostic reference index generator.")
    ap.add_argument("reference_dir", help="path to a project's reference/ directory")
    ap.add_argument("--stdout", action="store_true", help="print to stdout instead of writing index.md")
    args = ap.parse_args()

    if not os.path.isdir(args.reference_dir):
        print(f"error: not a directory: {args.reference_dir}", file=sys.stderr)
        return 2

    content = build_index(args.reference_dir)
    if args.stdout:
        sys.stdout.write(content)
        return 0

    index_path = os.path.join(os.path.normpath(args.reference_dir), "index.md")
    with open(index_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Updated {index_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
